"""init table

Revision ID: 96aa146995e1
Revises: 
Create Date: 2026-04-12 08:51:04.083567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96aa146995e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escrows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_ref', sa.String(length=255), nullable=False),
    sa.Column('escrow_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('initiator_actor_type', sa.String(length=20), nullable=False),
    sa.Column('initiator_id', sa.UUID(), nullable=True),
    sa.Column('initiator_org_id', sa.UUID(), nullable=True),
    sa.Column('receiver_id', sa.UUID(), nullable=True),
    sa.Column('receiver_email', sa.String(length=255), nullable=True),
    sa.Column('initiator_role', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('fee_amount', sa.BigInteger(), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('inspection_period', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispute_window', sa.Integer(), nullable=False),
    sa.Column('how_dispute_handled', sa.String(length=20), nullable=False),
    sa.Column('who_pays_fees', sa.String(length=10), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('invite_token_hash', sa.String(length=128), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invite_token_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offer_version', sa.Integer(), nullable=False),
    sa.Column('counter_status', sa.String(length=30), nullable=False),
    sa.Column('active_counter_offer_version', sa.Integer(), nullable=True),
    sa.Column('last_countered_by_id', sa.UUID(), nullable=True),
    sa.Column('last_countered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initiator_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receiver_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('funded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("((initiator_actor_type = 'user' AND initiator_id IS NOT NULL AND initiator_org_id IS NULL) OR (initiator_actor_type = 'organization' AND initiator_id IS NULL AND initiator_org_id IS NOT NULL))", name='ck_escrows_initiator_actor_consistency'),
    sa.CheckConstraint("counter_status IN ('none', 'awaiting_initiator', 'awaiting_counterparty', 'accepted', 'rejected')", name='ck_escrows_counter_status'),
    sa.CheckConstraint("escrow_type IN ('onetime', 'milestone', 'recurring')", name='ck_escrows_type'),
    sa.CheckConstraint("how_dispute_handled IN ('platform', 'arbitrator', 'mutual')", name='ck_escrows_dispute_handled'),
    sa.CheckConstraint("initiator_actor_type IN ('user', 'organization')", name='ck_escrows_initiator_actor_type'),
    sa.CheckConstraint("initiator_role IN ('buyer', 'seller', 'broker')", name='ck_escrows_initiator_role'),
    sa.CheckConstraint("status IN ('invited', 'counter_pending_initiator', 'counter_pending_counterparty', 'rejected', 'expired', 'pending', 'active', 'completed', 'disputed', 'cancelled', 'refunded')", name='ck_escrows_status'),
    sa.CheckConstraint("who_pays_fees IN ('buyer', 'seller', 'split')", name='ck_escrows_who_pays_fees'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_ref')
    )
    op.create_index(op.f('ix_escrows_initiator_id'), 'escrows', ['initiator_id'], unique=False)
    op.create_index(op.f('ix_escrows_initiator_org_id'), 'escrows', ['initiator_org_id'], unique=False)
    op.create_table('counter_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escrow_id', sa.UUID(), nullable=False),
    sa.Column('offer_version', sa.Integer(), nullable=False),
    sa.Column('proposed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('proposed_to_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('responded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('inspection_period', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispute_window', sa.Integer(), nullable=False),
    sa.Column('how_dispute_handled', sa.String(length=20), nullable=False),
    sa.Column('who_pays_fees', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending_response', 'accepted', 'rejected', 'countered_again')", name='ck_counter_offers_status'),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counter_offers_escrow_id'), 'counter_offers', ['escrow_id'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escrow_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspection_hrs', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'delivered', 'completed', 'disputed')", name='ck_milestones_status'),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_escrow_id'), 'milestones', ['escrow_id'], unique=False)
    op.create_table('recurring_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escrow_id', sa.UUID(), nullable=False),
    sa.Column('cycle_interval', sa.String(length=20), nullable=False),
    sa.Column('due_day_of_month', sa.Integer(), nullable=True),
    sa.Column('expected_amount', sa.BigInteger(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_contributors', sa.Integer(), nullable=False),
    sa.Column('max_contributors', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("cycle_interval IN ('daily', 'weekly', 'monthly')", name='ck_recurring_cycle_interval'),
    sa.CheckConstraint("status IN ('pending', 'active', 'completed')", name='ck_recurring_cycle_status'),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_cycles_escrow_id'), 'recurring_cycles', ['escrow_id'], unique=False)
    op.create_table('recurring_contributors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('expected_amount', sa.BigInteger(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['recurring_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_contributors_cycle_id'), 'recurring_contributors', ['cycle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_contributors_cycle_id'), table_name='recurring_contributors')
    op.drop_table('recurring_contributors')
    op.drop_index(op.f('ix_recurring_cycles_escrow_id'), table_name='recurring_cycles')
    op.drop_table('recurring_cycles')
    op.drop_index(op.f('ix_milestones_escrow_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_counter_offers_escrow_id'), table_name='counter_offers')
    op.drop_table('counter_offers')
    op.drop_index(op.f('ix_escrows_initiator_org_id'), table_name='escrows')
    op.drop_index(op.f('ix_escrows_initiator_id'), table_name='escrows')
    op.drop_table('escrows')
    # ### end Alembic commands ###
