"""init tables

Revision ID: 4fc01a0e27c2
Revises: 
Create Date: 2026-04-08 19:08:23.682094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc01a0e27c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_action_logs_action'), 'admin_action_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_admin_id'), 'admin_action_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_target_id'), 'admin_action_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_target_type'), 'admin_action_logs', ['target_type'], unique=False)
    op.create_table('admin_dispute_evidence_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dispute_id', sa.Uuid(), nullable=False),
    sa.Column('requested_from_user_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_dispute_evidence_requests_dispute_id'), 'admin_dispute_evidence_requests', ['dispute_id'], unique=False)
    op.create_index(op.f('ix_admin_dispute_evidence_requests_requested_by'), 'admin_dispute_evidence_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_admin_dispute_evidence_requests_requested_from_user_id'), 'admin_dispute_evidence_requests', ['requested_from_user_id'], unique=False)
    op.create_index(op.f('ix_admin_dispute_evidence_requests_status'), 'admin_dispute_evidence_requests', ['status'], unique=False)
    op.create_table('admin_dispute_internal_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dispute_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_dispute_internal_notes_author_id'), 'admin_dispute_internal_notes', ['author_id'], unique=False)
    op.create_index(op.f('ix_admin_dispute_internal_notes_dispute_id'), 'admin_dispute_internal_notes', ['dispute_id'], unique=False)
    op.create_table('admin_dispute_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dispute_id', sa.Uuid(), nullable=False),
    sa.Column('escrow_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('raised_by', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_dispute_queue_assignee_id'), 'admin_dispute_queue', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_admin_dispute_queue_dispute_id'), 'admin_dispute_queue', ['dispute_id'], unique=True)
    op.create_index(op.f('ix_admin_dispute_queue_escrow_id'), 'admin_dispute_queue', ['escrow_id'], unique=False)
    op.create_index(op.f('ix_admin_dispute_queue_priority'), 'admin_dispute_queue', ['priority'], unique=False)
    op.create_index(op.f('ix_admin_dispute_queue_raised_by'), 'admin_dispute_queue', ['raised_by'], unique=False)
    op.create_index(op.f('ix_admin_dispute_queue_status'), 'admin_dispute_queue', ['status'], unique=False)
    op.create_table('admin_dispute_resolution_rationales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dispute_id', sa.Uuid(), nullable=False),
    sa.Column('escrow_id', sa.Uuid(), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('apply_fee_refund', sa.Boolean(), nullable=False),
    sa.Column('fee_refund_status', sa.String(length=30), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_dispute_resolution_rationales_decided_by'), 'admin_dispute_resolution_rationales', ['decided_by'], unique=False)
    op.create_index(op.f('ix_admin_dispute_resolution_rationales_dispute_id'), 'admin_dispute_resolution_rationales', ['dispute_id'], unique=False)
    op.create_index(op.f('ix_admin_dispute_resolution_rationales_escrow_id'), 'admin_dispute_resolution_rationales', ['escrow_id'], unique=False)
    op.create_index(op.f('ix_admin_dispute_resolution_rationales_resolution'), 'admin_dispute_resolution_rationales', ['resolution'], unique=False)
    op.create_table('admin_idempotency_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action', 'idempotency_key', name='uq_admin_idempotency_action_key')
    )
    op.create_index(op.f('ix_admin_idempotency_keys_action'), 'admin_idempotency_keys', ['action'], unique=False)
    op.create_index(op.f('ix_admin_idempotency_keys_actor_id'), 'admin_idempotency_keys', ['actor_id'], unique=False)
    op.create_index(op.f('ix_admin_idempotency_keys_idempotency_key'), 'admin_idempotency_keys', ['idempotency_key'], unique=False)
    op.create_table('admin_payout_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payout_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_payout_queue_assignee_id'), 'admin_payout_queue', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_admin_payout_queue_currency'), 'admin_payout_queue', ['currency'], unique=False)
    op.create_index(op.f('ix_admin_payout_queue_payout_id'), 'admin_payout_queue', ['payout_id'], unique=True)
    op.create_index(op.f('ix_admin_payout_queue_priority'), 'admin_payout_queue', ['priority'], unique=False)
    op.create_index(op.f('ix_admin_payout_queue_status'), 'admin_payout_queue', ['status'], unique=False)
    op.create_index(op.f('ix_admin_payout_queue_user_id'), 'admin_payout_queue', ['user_id'], unique=False)
    op.create_index(op.f('ix_admin_payout_queue_wallet_id'), 'admin_payout_queue', ['wallet_id'], unique=False)
    op.create_table('admin_report_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('export_format', sa.String(length=10), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result_url', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_report_jobs_report_type'), 'admin_report_jobs', ['report_type'], unique=False)
    op.create_index(op.f('ix_admin_report_jobs_requested_by'), 'admin_report_jobs', ['requested_by'], unique=False)
    op.create_index(op.f('ix_admin_report_jobs_status'), 'admin_report_jobs', ['status'], unique=False)
    op.create_table('admin_review_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('escalated_from_case_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_review_cases_assignee_id'), 'admin_review_cases', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_admin_review_cases_created_by'), 'admin_review_cases', ['created_by'], unique=False)
    op.create_index(op.f('ix_admin_review_cases_priority'), 'admin_review_cases', ['priority'], unique=False)
    op.create_index(op.f('ix_admin_review_cases_status'), 'admin_review_cases', ['status'], unique=False)
    op.create_index(op.f('ix_admin_review_cases_subject_id'), 'admin_review_cases', ['subject_id'], unique=False)
    op.create_index(op.f('ix_admin_review_cases_subject_type'), 'admin_review_cases', ['subject_type'], unique=False)
    op.create_table('admin_risk_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('flag', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_risk_flags_created_by'), 'admin_risk_flags', ['created_by'], unique=False)
    op.create_index(op.f('ix_admin_risk_flags_flag'), 'admin_risk_flags', ['flag'], unique=False)
    op.create_index(op.f('ix_admin_risk_flags_severity'), 'admin_risk_flags', ['severity'], unique=False)
    op.create_index(op.f('ix_admin_risk_flags_status'), 'admin_risk_flags', ['status'], unique=False)
    op.create_index(op.f('ix_admin_risk_flags_user_id'), 'admin_risk_flags', ['user_id'], unique=False)
    op.create_table('admin_saved_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_saved_views_module'), 'admin_saved_views', ['module'], unique=False)
    op.create_index(op.f('ix_admin_saved_views_owner_id'), 'admin_saved_views', ['owner_id'], unique=False)
    op.create_table('admin_system_config_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_key', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('previous_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key', 'version', name='uq_admin_system_config_history_key_version')
    )
    op.create_index(op.f('ix_admin_system_config_history_action'), 'admin_system_config_history', ['action'], unique=False)
    op.create_index(op.f('ix_admin_system_config_history_changed_by'), 'admin_system_config_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_admin_system_config_history_config_key'), 'admin_system_config_history', ['config_key'], unique=False)
    op.create_index(op.f('ix_admin_system_config_history_version'), 'admin_system_config_history', ['version'], unique=False)
    op.create_table('admin_system_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_system_configs_config_key'), 'admin_system_configs', ['config_key'], unique=True)
    op.create_index(op.f('ix_admin_system_configs_updated_by'), 'admin_system_configs', ['updated_by'], unique=False)
    op.create_table('admin_moderation_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['admin_review_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_moderation_notes_case_id'), 'admin_moderation_notes', ['case_id'], unique=False)
    op.create_index(op.f('ix_admin_moderation_notes_created_by'), 'admin_moderation_notes', ['created_by'], unique=False)
    op.create_index(op.f('ix_admin_moderation_notes_target_id'), 'admin_moderation_notes', ['target_id'], unique=False)
    op.create_index(op.f('ix_admin_moderation_notes_target_type'), 'admin_moderation_notes', ['target_type'], unique=False)
    op.create_index(op.f('ix_admin_moderation_notes_visibility'), 'admin_moderation_notes', ['visibility'], unique=False)
    op.create_table('admin_verification_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('overridden_by', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('review_case_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_case_id'], ['admin_review_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_verification_overrides_idempotency_key'), 'admin_verification_overrides', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_admin_verification_overrides_overridden_by'), 'admin_verification_overrides', ['overridden_by'], unique=False)
    op.create_index(op.f('ix_admin_verification_overrides_review_case_id'), 'admin_verification_overrides', ['review_case_id'], unique=False)
    op.create_index(op.f('ix_admin_verification_overrides_user_id'), 'admin_verification_overrides', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_verification_overrides_user_id'), table_name='admin_verification_overrides')
    op.drop_index(op.f('ix_admin_verification_overrides_review_case_id'), table_name='admin_verification_overrides')
    op.drop_index(op.f('ix_admin_verification_overrides_overridden_by'), table_name='admin_verification_overrides')
    op.drop_index(op.f('ix_admin_verification_overrides_idempotency_key'), table_name='admin_verification_overrides')
    op.drop_table('admin_verification_overrides')
    op.drop_index(op.f('ix_admin_moderation_notes_visibility'), table_name='admin_moderation_notes')
    op.drop_index(op.f('ix_admin_moderation_notes_target_type'), table_name='admin_moderation_notes')
    op.drop_index(op.f('ix_admin_moderation_notes_target_id'), table_name='admin_moderation_notes')
    op.drop_index(op.f('ix_admin_moderation_notes_created_by'), table_name='admin_moderation_notes')
    op.drop_index(op.f('ix_admin_moderation_notes_case_id'), table_name='admin_moderation_notes')
    op.drop_table('admin_moderation_notes')
    op.drop_index(op.f('ix_admin_system_configs_updated_by'), table_name='admin_system_configs')
    op.drop_index(op.f('ix_admin_system_configs_config_key'), table_name='admin_system_configs')
    op.drop_table('admin_system_configs')
    op.drop_index(op.f('ix_admin_system_config_history_version'), table_name='admin_system_config_history')
    op.drop_index(op.f('ix_admin_system_config_history_config_key'), table_name='admin_system_config_history')
    op.drop_index(op.f('ix_admin_system_config_history_changed_by'), table_name='admin_system_config_history')
    op.drop_index(op.f('ix_admin_system_config_history_action'), table_name='admin_system_config_history')
    op.drop_table('admin_system_config_history')
    op.drop_index(op.f('ix_admin_saved_views_owner_id'), table_name='admin_saved_views')
    op.drop_index(op.f('ix_admin_saved_views_module'), table_name='admin_saved_views')
    op.drop_table('admin_saved_views')
    op.drop_index(op.f('ix_admin_risk_flags_user_id'), table_name='admin_risk_flags')
    op.drop_index(op.f('ix_admin_risk_flags_status'), table_name='admin_risk_flags')
    op.drop_index(op.f('ix_admin_risk_flags_severity'), table_name='admin_risk_flags')
    op.drop_index(op.f('ix_admin_risk_flags_flag'), table_name='admin_risk_flags')
    op.drop_index(op.f('ix_admin_risk_flags_created_by'), table_name='admin_risk_flags')
    op.drop_table('admin_risk_flags')
    op.drop_index(op.f('ix_admin_review_cases_subject_type'), table_name='admin_review_cases')
    op.drop_index(op.f('ix_admin_review_cases_subject_id'), table_name='admin_review_cases')
    op.drop_index(op.f('ix_admin_review_cases_status'), table_name='admin_review_cases')
    op.drop_index(op.f('ix_admin_review_cases_priority'), table_name='admin_review_cases')
    op.drop_index(op.f('ix_admin_review_cases_created_by'), table_name='admin_review_cases')
    op.drop_index(op.f('ix_admin_review_cases_assignee_id'), table_name='admin_review_cases')
    op.drop_table('admin_review_cases')
    op.drop_index(op.f('ix_admin_report_jobs_status'), table_name='admin_report_jobs')
    op.drop_index(op.f('ix_admin_report_jobs_requested_by'), table_name='admin_report_jobs')
    op.drop_index(op.f('ix_admin_report_jobs_report_type'), table_name='admin_report_jobs')
    op.drop_table('admin_report_jobs')
    op.drop_index(op.f('ix_admin_payout_queue_wallet_id'), table_name='admin_payout_queue')
    op.drop_index(op.f('ix_admin_payout_queue_user_id'), table_name='admin_payout_queue')
    op.drop_index(op.f('ix_admin_payout_queue_status'), table_name='admin_payout_queue')
    op.drop_index(op.f('ix_admin_payout_queue_priority'), table_name='admin_payout_queue')
    op.drop_index(op.f('ix_admin_payout_queue_payout_id'), table_name='admin_payout_queue')
    op.drop_index(op.f('ix_admin_payout_queue_currency'), table_name='admin_payout_queue')
    op.drop_index(op.f('ix_admin_payout_queue_assignee_id'), table_name='admin_payout_queue')
    op.drop_table('admin_payout_queue')
    op.drop_index(op.f('ix_admin_idempotency_keys_idempotency_key'), table_name='admin_idempotency_keys')
    op.drop_index(op.f('ix_admin_idempotency_keys_actor_id'), table_name='admin_idempotency_keys')
    op.drop_index(op.f('ix_admin_idempotency_keys_action'), table_name='admin_idempotency_keys')
    op.drop_table('admin_idempotency_keys')
    op.drop_index(op.f('ix_admin_dispute_resolution_rationales_resolution'), table_name='admin_dispute_resolution_rationales')
    op.drop_index(op.f('ix_admin_dispute_resolution_rationales_escrow_id'), table_name='admin_dispute_resolution_rationales')
    op.drop_index(op.f('ix_admin_dispute_resolution_rationales_dispute_id'), table_name='admin_dispute_resolution_rationales')
    op.drop_index(op.f('ix_admin_dispute_resolution_rationales_decided_by'), table_name='admin_dispute_resolution_rationales')
    op.drop_table('admin_dispute_resolution_rationales')
    op.drop_index(op.f('ix_admin_dispute_queue_status'), table_name='admin_dispute_queue')
    op.drop_index(op.f('ix_admin_dispute_queue_raised_by'), table_name='admin_dispute_queue')
    op.drop_index(op.f('ix_admin_dispute_queue_priority'), table_name='admin_dispute_queue')
    op.drop_index(op.f('ix_admin_dispute_queue_escrow_id'), table_name='admin_dispute_queue')
    op.drop_index(op.f('ix_admin_dispute_queue_dispute_id'), table_name='admin_dispute_queue')
    op.drop_index(op.f('ix_admin_dispute_queue_assignee_id'), table_name='admin_dispute_queue')
    op.drop_table('admin_dispute_queue')
    op.drop_index(op.f('ix_admin_dispute_internal_notes_dispute_id'), table_name='admin_dispute_internal_notes')
    op.drop_index(op.f('ix_admin_dispute_internal_notes_author_id'), table_name='admin_dispute_internal_notes')
    op.drop_table('admin_dispute_internal_notes')
    op.drop_index(op.f('ix_admin_dispute_evidence_requests_status'), table_name='admin_dispute_evidence_requests')
    op.drop_index(op.f('ix_admin_dispute_evidence_requests_requested_from_user_id'), table_name='admin_dispute_evidence_requests')
    op.drop_index(op.f('ix_admin_dispute_evidence_requests_requested_by'), table_name='admin_dispute_evidence_requests')
    op.drop_index(op.f('ix_admin_dispute_evidence_requests_dispute_id'), table_name='admin_dispute_evidence_requests')
    op.drop_table('admin_dispute_evidence_requests')
    op.drop_index(op.f('ix_admin_action_logs_target_type'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_target_id'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_admin_id'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_action'), table_name='admin_action_logs')
    op.drop_table('admin_action_logs')
    # ### end Alembic commands ###
