"""init tables

Revision ID: f1fd0e42cddb
Revises: 
Create Date: 2026-04-08 19:23:53.051675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fd0e42cddb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_fan_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fan', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fan')
    )
    op.create_index(op.f('ix_kyc_fan_claims_user_id'), 'kyc_fan_claims', ['user_id'], unique=False)
    op.create_table('kyc_identity_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fan', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('photo_object_key', sa.String(length=512), nullable=True),
    sa.Column('front_id_object_key', sa.String(length=512), nullable=True),
    sa.Column('back_id_object_key', sa.String(length=512), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fan')
    )
    op.create_index(op.f('ix_kyc_identity_records_user_id'), 'kyc_identity_records', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kyc_identity_records_user_id'), table_name='kyc_identity_records')
    op.drop_table('kyc_identity_records')
    op.drop_index(op.f('ix_kyc_fan_claims_user_id'), table_name='kyc_fan_claims')
    op.drop_table('kyc_fan_claims')
    # ### end Alembic commands ###
