# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.fee_pb2 as fee__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fee_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FeeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateFee = channel.unary_unary(
                '/fee.FeeService/CalculateFee',
                request_serializer=fee__pb2.CalculateFeeRequest.SerializeToString,
                response_deserializer=fee__pb2.CalculateFeeResponse.FromString,
                _registered_method=True)
        self.RecordFee = channel.unary_unary(
                '/fee.FeeService/RecordFee',
                request_serializer=fee__pb2.RecordFeeRequest.SerializeToString,
                response_deserializer=fee__pb2.FeeLedgerResponse.FromString,
                _registered_method=True)
        self.RefundFeeForEscrow = channel.unary_unary(
                '/fee.FeeService/RefundFeeForEscrow',
                request_serializer=fee__pb2.RefundFeeForEscrowRequest.SerializeToString,
                response_deserializer=fee__pb2.RefundFeeForEscrowResponse.FromString,
                _registered_method=True)


class FeeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateFee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordFee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefundFeeForEscrow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateFee': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateFee,
                    request_deserializer=fee__pb2.CalculateFeeRequest.FromString,
                    response_serializer=fee__pb2.CalculateFeeResponse.SerializeToString,
            ),
            'RecordFee': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordFee,
                    request_deserializer=fee__pb2.RecordFeeRequest.FromString,
                    response_serializer=fee__pb2.FeeLedgerResponse.SerializeToString,
            ),
            'RefundFeeForEscrow': grpc.unary_unary_rpc_method_handler(
                    servicer.RefundFeeForEscrow,
                    request_deserializer=fee__pb2.RefundFeeForEscrowRequest.FromString,
                    response_serializer=fee__pb2.RefundFeeForEscrowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fee.FeeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fee.FeeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fee.FeeService/CalculateFee',
            fee__pb2.CalculateFeeRequest.SerializeToString,
            fee__pb2.CalculateFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fee.FeeService/RecordFee',
            fee__pb2.RecordFeeRequest.SerializeToString,
            fee__pb2.FeeLedgerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefundFeeForEscrow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fee.FeeService/RefundFeeForEscrow',
            fee__pb2.RefundFeeForEscrowRequest.SerializeToString,
            fee__pb2.RefundFeeForEscrowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
