# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.storage_pb2 as storage__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in storage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeneratePresignedUploadUrl = channel.unary_unary(
                '/storage.StorageService/GeneratePresignedUploadUrl',
                request_serializer=storage__pb2.PresignUploadRequest.SerializeToString,
                response_deserializer=storage__pb2.PresignUrlResponse.FromString,
                _registered_method=True)
        self.GeneratePresignedDownloadUrl = channel.unary_unary(
                '/storage.StorageService/GeneratePresignedDownloadUrl',
                request_serializer=storage__pb2.PresignDownloadRequest.SerializeToString,
                response_deserializer=storage__pb2.PresignUrlResponse.FromString,
                _registered_method=True)


class StorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GeneratePresignedUploadUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeneratePresignedDownloadUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeneratePresignedUploadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePresignedUploadUrl,
                    request_deserializer=storage__pb2.PresignUploadRequest.FromString,
                    response_serializer=storage__pb2.PresignUrlResponse.SerializeToString,
            ),
            'GeneratePresignedDownloadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePresignedDownloadUrl,
                    request_deserializer=storage__pb2.PresignDownloadRequest.FromString,
                    response_serializer=storage__pb2.PresignUrlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storage.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('storage.StorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GeneratePresignedUploadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GeneratePresignedUploadUrl',
            storage__pb2.PresignUploadRequest.SerializeToString,
            storage__pb2.PresignUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GeneratePresignedDownloadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GeneratePresignedDownloadUrl',
            storage__pb2.PresignDownloadRequest.SerializeToString,
            storage__pb2.PresignUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
