# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"M\n\rTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x0e\n\x06scopes\x18\x04 \x03(\t\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"w\n\x0cUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x13\n\x0bis_verified\x18\x04 \x01(\x08\x12\x11\n\tis_banned\x18\x05 \x01(\x08\x12\x11\n\tkyc_level\x18\x06 \x01(\x05\"\x1d\n\x0c\x45mailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"6\n\x13\x45mailExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t2\xc2\x01\n\rAuthValidator\x12\x38\n\rValidateToken\x12\x12.auth.TokenRequest\x1a\x13.auth.TokenResponse\x12\x34\n\x0bGetUserById\x12\x11.auth.UserRequest\x1a\x12.auth.UserResponse\x12\x41\n\x10\x43heckEmailExists\x12\x12.auth.EmailRequest\x1a\x19.auth.EmailExistsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENREQUEST']._serialized_start=20
  _globals['_TOKENREQUEST']._serialized_end=49
  _globals['_TOKENRESPONSE']._serialized_start=51
  _globals['_TOKENRESPONSE']._serialized_end=128
  _globals['_USERREQUEST']._serialized_start=130
  _globals['_USERREQUEST']._serialized_end=160
  _globals['_USERRESPONSE']._serialized_start=162
  _globals['_USERRESPONSE']._serialized_end=281
  _globals['_EMAILREQUEST']._serialized_start=283
  _globals['_EMAILREQUEST']._serialized_end=312
  _globals['_EMAILEXISTSRESPONSE']._serialized_start=314
  _globals['_EMAILEXISTSRESPONSE']._serialized_end=368
  _globals['_AUTHVALIDATOR']._serialized_start=371
  _globals['_AUTHVALIDATOR']._serialized_end=565
# @@protoc_insertion_point(module_scope)
