"""init table

Revision ID: 73b218531735
Revises: 
Create Date: 2026-04-13 19:41:53.557320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b218531735'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_members',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('org_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner','admin','member')", name='ck_organization_members_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_organization_members_org_user')
    )
    op.create_index(op.f('ix_organization_members_org_id'), 'organization_members', ['org_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('owner_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('tin', sa.String(length=50), nullable=True),
    sa.Column('kyb_level', sa.SmallInteger(), nullable=False),
    sa.Column('kyb_status', sa.String(length=20), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.SmallInteger(), nullable=False),
    sa.Column('public_key', sa.String(length=255), nullable=False),
    sa.Column('secret_key_hash', sa.String(length=512), nullable=False),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('public_key'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('tin')
    )
    op.create_index(op.f('ix_organizations_owner_id'), 'organizations', ['owner_id'], unique=False)
    op.create_table('organization_role_permissions',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('org_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('permission_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner','admin','member')", name='ck_organization_role_permissions_role'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'role', 'permission_key', name='uq_organization_role_permissions_org_role_permission')
    )
    op.create_index(op.f('ix_organization_role_permissions_org_id'), 'organization_role_permissions', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_role_permissions_org_id'), table_name='organization_role_permissions')
    op.drop_table('organization_role_permissions')
    op.drop_index(op.f('ix_organizations_owner_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_organization_members_org_id'), table_name='organization_members')
    op.drop_table('organization_members')
    # ### end Alembic commands ###
