# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.wallet_pb2 as wallet__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in wallet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WalletServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBalance = channel.unary_unary(
                '/wallet.WalletService/GetBalance',
                request_serializer=wallet__pb2.BalanceRequest.SerializeToString,
                response_deserializer=wallet__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.GetWalletByOwner = channel.unary_unary(
                '/wallet.WalletService/GetWalletByOwner',
                request_serializer=wallet__pb2.OwnerWalletRequest.SerializeToString,
                response_deserializer=wallet__pb2.OwnerWalletResponse.FromString,
                _registered_method=True)
        self.LockFunds = channel.unary_unary(
                '/wallet.WalletService/LockFunds',
                request_serializer=wallet__pb2.FundsRequest.SerializeToString,
                response_deserializer=wallet__pb2.FundsResponse.FromString,
                _registered_method=True)
        self.UnlockFunds = channel.unary_unary(
                '/wallet.WalletService/UnlockFunds',
                request_serializer=wallet__pb2.FundsRequest.SerializeToString,
                response_deserializer=wallet__pb2.FundsResponse.FromString,
                _registered_method=True)
        self.ReleaseFunds = channel.unary_unary(
                '/wallet.WalletService/ReleaseFunds',
                request_serializer=wallet__pb2.ReleaseRequest.SerializeToString,
                response_deserializer=wallet__pb2.FundsResponse.FromString,
                _registered_method=True)
        self.FundWallet = channel.unary_unary(
                '/wallet.WalletService/FundWallet',
                request_serializer=wallet__pb2.FundRequest.SerializeToString,
                response_deserializer=wallet__pb2.FundsResponse.FromString,
                _registered_method=True)
        self.DeductBalance = channel.unary_unary(
                '/wallet.WalletService/DeductBalance',
                request_serializer=wallet__pb2.DeductRequest.SerializeToString,
                response_deserializer=wallet__pb2.DeductResponse.FromString,
                _registered_method=True)


class WalletServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWalletByOwner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LockFunds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockFunds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseFunds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeductBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WalletServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=wallet__pb2.BalanceRequest.FromString,
                    response_serializer=wallet__pb2.BalanceResponse.SerializeToString,
            ),
            'GetWalletByOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWalletByOwner,
                    request_deserializer=wallet__pb2.OwnerWalletRequest.FromString,
                    response_serializer=wallet__pb2.OwnerWalletResponse.SerializeToString,
            ),
            'LockFunds': grpc.unary_unary_rpc_method_handler(
                    servicer.LockFunds,
                    request_deserializer=wallet__pb2.FundsRequest.FromString,
                    response_serializer=wallet__pb2.FundsResponse.SerializeToString,
            ),
            'UnlockFunds': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockFunds,
                    request_deserializer=wallet__pb2.FundsRequest.FromString,
                    response_serializer=wallet__pb2.FundsResponse.SerializeToString,
            ),
            'ReleaseFunds': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseFunds,
                    request_deserializer=wallet__pb2.ReleaseRequest.FromString,
                    response_serializer=wallet__pb2.FundsResponse.SerializeToString,
            ),
            'FundWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.FundWallet,
                    request_deserializer=wallet__pb2.FundRequest.FromString,
                    response_serializer=wallet__pb2.FundsResponse.SerializeToString,
            ),
            'DeductBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.DeductBalance,
                    request_deserializer=wallet__pb2.DeductRequest.FromString,
                    response_serializer=wallet__pb2.DeductResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wallet.WalletService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wallet.WalletService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WalletService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/GetBalance',
            wallet__pb2.BalanceRequest.SerializeToString,
            wallet__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWalletByOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/GetWalletByOwner',
            wallet__pb2.OwnerWalletRequest.SerializeToString,
            wallet__pb2.OwnerWalletResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LockFunds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/LockFunds',
            wallet__pb2.FundsRequest.SerializeToString,
            wallet__pb2.FundsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlockFunds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/UnlockFunds',
            wallet__pb2.FundsRequest.SerializeToString,
            wallet__pb2.FundsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseFunds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/ReleaseFunds',
            wallet__pb2.ReleaseRequest.SerializeToString,
            wallet__pb2.FundsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FundWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/FundWallet',
            wallet__pb2.FundRequest.SerializeToString,
            wallet__pb2.FundsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeductBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/DeductBalance',
            wallet__pb2.DeductRequest.SerializeToString,
            wallet__pb2.DeductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
