# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.organization_pb2 as organization__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in organization_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrganizationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckOrgMembership = channel.unary_unary(
                '/organization.OrganizationService/CheckOrgMembership',
                request_serializer=organization__pb2.OrgMembershipRequest.SerializeToString,
                response_deserializer=organization__pb2.OrgMembershipExistsResponse.FromString,
                _registered_method=True)
        self.CheckOrganizationExists = channel.unary_unary(
                '/organization.OrganizationService/CheckOrganizationExists',
                request_serializer=organization__pb2.OrganizationExistsRequest.SerializeToString,
                response_deserializer=organization__pb2.OrganizationExistsResponse.FromString,
                _registered_method=True)
        self.VerifySecretKey = channel.unary_unary(
                '/organization.OrganizationService/VerifySecretKey',
                request_serializer=organization__pb2.VerifySecretKeyRequest.SerializeToString,
                response_deserializer=organization__pb2.VerifySecretKeyResponse.FromString,
                _registered_method=True)


class OrganizationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckOrgMembership(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckOrganizationExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifySecretKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrganizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckOrgMembership': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOrgMembership,
                    request_deserializer=organization__pb2.OrgMembershipRequest.FromString,
                    response_serializer=organization__pb2.OrgMembershipExistsResponse.SerializeToString,
            ),
            'CheckOrganizationExists': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOrganizationExists,
                    request_deserializer=organization__pb2.OrganizationExistsRequest.FromString,
                    response_serializer=organization__pb2.OrganizationExistsResponse.SerializeToString,
            ),
            'VerifySecretKey': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifySecretKey,
                    request_deserializer=organization__pb2.VerifySecretKeyRequest.FromString,
                    response_serializer=organization__pb2.VerifySecretKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'organization.OrganizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('organization.OrganizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrganizationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckOrgMembership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/organization.OrganizationService/CheckOrgMembership',
            organization__pb2.OrgMembershipRequest.SerializeToString,
            organization__pb2.OrgMembershipExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckOrganizationExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/organization.OrganizationService/CheckOrganizationExists',
            organization__pb2.OrganizationExistsRequest.SerializeToString,
            organization__pb2.OrganizationExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifySecretKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/organization.OrganizationService/VerifySecretKey',
            organization__pb2.VerifySecretKeyRequest.SerializeToString,
            organization__pb2.VerifySecretKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
