# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment_provider.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payment_provider.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16payment_provider.proto\x12\x10payment_provider\"p\n\x0f\x43heckoutRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\x12\x15\n\rmetadata_json\x18\x03 \x01(\t\x12\x10\n\x08provider\x18\x04 \x01(\t\x12\x12\n\nreturn_url\x18\x05 \x01(\t\"R\n\x10\x43heckoutResponse\x12\x13\n\x0bpayment_url\x18\x01 \x01(\t\x12\x17\n\x0ftransaction_ref\x18\x02 \x01(\t\x12\x10\n\x08provider\x18\x03 \x01(\t\"4\n\rVerifyRequest\x12\x11\n\treference\x18\x01 \x01(\t\x12\x10\n\x08provider\x18\x02 \x01(\t\"1\n\x0eVerifyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x99\x01\n\x0fTransferRequest\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x01 \x01(\t\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x11\n\treference\x18\x05 \x01(\t\x12\x11\n\tbank_code\x18\x06 \x01(\x03\x12\x10\n\x08provider\x18\x07 \x01(\t\"Z\n\x10TransferResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0cprovider_ref\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"?\n\x15TransferVerifyRequest\x12\x14\n\x0cprovider_ref\x18\x01 \x01(\t\x12\x10\n\x08provider\x18\x02 \x01(\t\"9\n\x16TransferVerifyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t2\x85\x03\n\x16PaymentProviderService\x12W\n\x0e\x43reateCheckout\x12!.payment_provider.CheckoutRequest\x1a\".payment_provider.CheckoutResponse\x12R\n\rVerifyPayment\x12\x1f.payment_provider.VerifyRequest\x1a .payment_provider.VerifyResponse\x12Y\n\x10InitiateTransfer\x12!.payment_provider.TransferRequest\x1a\".payment_provider.TransferResponse\x12\x63\n\x0eVerifyTransfer\x12\'.payment_provider.TransferVerifyRequest\x1a(.payment_provider.TransferVerifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_provider_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKOUTREQUEST']._serialized_start=44
  _globals['_CHECKOUTREQUEST']._serialized_end=156
  _globals['_CHECKOUTRESPONSE']._serialized_start=158
  _globals['_CHECKOUTRESPONSE']._serialized_end=240
  _globals['_VERIFYREQUEST']._serialized_start=242
  _globals['_VERIFYREQUEST']._serialized_end=294
  _globals['_VERIFYRESPONSE']._serialized_start=296
  _globals['_VERIFYRESPONSE']._serialized_end=345
  _globals['_TRANSFERREQUEST']._serialized_start=348
  _globals['_TRANSFERREQUEST']._serialized_end=501
  _globals['_TRANSFERRESPONSE']._serialized_start=503
  _globals['_TRANSFERRESPONSE']._serialized_end=593
  _globals['_TRANSFERVERIFYREQUEST']._serialized_start=595
  _globals['_TRANSFERVERIFYREQUEST']._serialized_end=658
  _globals['_TRANSFERVERIFYRESPONSE']._serialized_start=660
  _globals['_TRANSFERVERIFYRESPONSE']._serialized_end=717
  _globals['_PAYMENTPROVIDERSERVICE']._serialized_start=720
  _globals['_PAYMENTPROVIDERSERVICE']._serialized_end=1109
# @@protoc_insertion_point(module_scope)
