# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audit.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udit.proto\x12\x05\x61udit\x1a\x1cgoogle/protobuf/struct.proto\"\xda\x01\n\x13\x45mitAuditLogRequest\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x10\n\x08resource\x18\x03 \x01(\t\x12\x13\n\x0bresource_id\x18\x04 \x01(\t\x12\'\n\x06\x62\x65\x66ore\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\x12&\n\x05\x61\x66ter\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\x12)\n\x08metadata\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\"H\n\x14\x45mitAuditLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06log_id\x18\x03 \x01(\t2W\n\x0c\x41uditService\x12G\n\x0c\x45mitAuditLog\x12\x1a.audit.EmitAuditLogRequest\x1a\x1b.audit.EmitAuditLogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMITAUDITLOGREQUEST']._serialized_start=53
  _globals['_EMITAUDITLOGREQUEST']._serialized_end=271
  _globals['_EMITAUDITLOGRESPONSE']._serialized_start=273
  _globals['_EMITAUDITLOGRESPONSE']._serialized_end=345
  _globals['_AUDITSERVICE']._serialized_start=347
  _globals['_AUDITSERVICE']._serialized_end=434
# @@protoc_insertion_point(module_scope)
