# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: escrow.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'escrow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65scrow.proto\x12\x06\x65scrow\"\"\n\rEscrowRequest\x12\x11\n\tescrow_id\x18\x01 \x01(\t\"L\n\x11TransitionRequest\x12\x11\n\tescrow_id\x18\x01 \x01(\t\x12\x12\n\nnew_status\x18\x02 \x01(\t\x12\x10\n\x08\x61\x63tor_id\x18\x03 \x01(\t\">\n\x18\x45scrowAssociationRequest\x12\x11\n\tescrow_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"=\n\x19\x45scrowAssociationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xb7\x01\n\x0e\x45scrowResponse\x12\x11\n\tescrow_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x13\n\x0b\x65scrow_type\x18\x03 \x01(\t\x12\x14\n\x0cinitiator_id\x18\x04 \x01(\t\x12\x13\n\x0breceiver_id\x18\x05 \x01(\t\x12\x0e\n\x06\x61mount\x18\x06 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x07 \x01(\t\x12\x0f\n\x07success\x18\x08 \x01(\x08\x12\x0f\n\x07message\x18\t \x01(\t2\xf2\x01\n\rEscrowService\x12:\n\tGetEscrow\x12\x15.escrow.EscrowRequest\x1a\x16.escrow.EscrowResponse\x12\x45\n\x10TransitionStatus\x12\x19.escrow.TransitionRequest\x1a\x16.escrow.EscrowResponse\x12^\n\x17\x41ssociateUserWithEscrow\x12 .escrow.EscrowAssociationRequest\x1a!.escrow.EscrowAssociationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'escrow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ESCROWREQUEST']._serialized_start=24
  _globals['_ESCROWREQUEST']._serialized_end=58
  _globals['_TRANSITIONREQUEST']._serialized_start=60
  _globals['_TRANSITIONREQUEST']._serialized_end=136
  _globals['_ESCROWASSOCIATIONREQUEST']._serialized_start=138
  _globals['_ESCROWASSOCIATIONREQUEST']._serialized_end=200
  _globals['_ESCROWASSOCIATIONRESPONSE']._serialized_start=202
  _globals['_ESCROWASSOCIATIONRESPONSE']._serialized_end=263
  _globals['_ESCROWRESPONSE']._serialized_start=266
  _globals['_ESCROWRESPONSE']._serialized_end=449
  _globals['_ESCROWSERVICE']._serialized_start=452
  _globals['_ESCROWSERVICE']._serialized_end=694
# @@protoc_insertion_point(module_scope)
