# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.payout_pb2 as payout__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in payout_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PayoutServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListPayouts = channel.unary_unary(
                '/payout.PayoutService/ListPayouts',
                request_serializer=payout__pb2.ListPayoutsRequest.SerializeToString,
                response_deserializer=payout__pb2.ListPayoutsResponse.FromString,
                _registered_method=True)
        self.RetryPayoutTransfer = channel.unary_unary(
                '/payout.PayoutService/RetryPayoutTransfer',
                request_serializer=payout__pb2.RetryPayoutTransferRequest.SerializeToString,
                response_deserializer=payout__pb2.PayoutResponse.FromString,
                _registered_method=True)


class PayoutServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListPayouts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetryPayoutTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PayoutServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListPayouts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPayouts,
                    request_deserializer=payout__pb2.ListPayoutsRequest.FromString,
                    response_serializer=payout__pb2.ListPayoutsResponse.SerializeToString,
            ),
            'RetryPayoutTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.RetryPayoutTransfer,
                    request_deserializer=payout__pb2.RetryPayoutTransferRequest.FromString,
                    response_serializer=payout__pb2.PayoutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payout.PayoutService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payout.PayoutService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PayoutService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListPayouts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payout.PayoutService/ListPayouts',
            payout__pb2.ListPayoutsRequest.SerializeToString,
            payout__pb2.ListPayoutsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetryPayoutTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payout.PayoutService/RetryPayoutTransfer',
            payout__pb2.RetryPayoutTransferRequest.SerializeToString,
            payout__pb2.PayoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
