# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payout.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payout.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpayout.proto\x12\x06payout\"A\n\x12ListPayoutsRequest\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\"/\n\x1aRetryPayoutTransferRequest\x12\x11\n\tpayout_id\x18\x01 \x01(\t\"\x9b\x02\n\x0ePayoutResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x11\n\twallet_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x11\n\tbank_code\x18\x06 \x01(\t\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x07 \x01(\t\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x08 \x01(\t\x12\x0e\n\x06status\x18\t \x01(\t\x12\x10\n\x08provider\x18\n \x01(\t\x12\x14\n\x0cprovider_ref\x18\x0b \x01(\t\x12\x16\n\x0e\x66\x61ilure_reason\x18\x0c \x01(\t\x12\x12\n\ncreated_at\x18\r \x01(\t\x12\x12\n\nupdated_at\x18\x0e \x01(\t\"w\n\x13ListPayoutsResponse\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.payout.PayoutResponse\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\r\n\x05limit\x18\x04 \x01(\x05\x12\r\n\x05pages\x18\x05 \x01(\x05\x32\xaa\x01\n\rPayoutService\x12\x46\n\x0bListPayouts\x12\x1a.payout.ListPayoutsRequest\x1a\x1b.payout.ListPayoutsResponse\x12Q\n\x13RetryPayoutTransfer\x12\".payout.RetryPayoutTransferRequest\x1a\x16.payout.PayoutResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payout_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTPAYOUTSREQUEST']._serialized_start=24
  _globals['_LISTPAYOUTSREQUEST']._serialized_end=89
  _globals['_RETRYPAYOUTTRANSFERREQUEST']._serialized_start=91
  _globals['_RETRYPAYOUTTRANSFERREQUEST']._serialized_end=138
  _globals['_PAYOUTRESPONSE']._serialized_start=141
  _globals['_PAYOUTRESPONSE']._serialized_end=424
  _globals['_LISTPAYOUTSRESPONSE']._serialized_start=426
  _globals['_LISTPAYOUTSRESPONSE']._serialized_end=545
  _globals['_PAYOUTSERVICE']._serialized_start=548
  _globals['_PAYOUTSERVICE']._serialized_end=718
# @@protoc_insertion_point(module_scope)
