# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.dispute_pb2 as dispute__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dispute_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DisputeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDisputes = channel.unary_unary(
                '/dispute.DisputeService/ListDisputes',
                request_serializer=dispute__pb2.ListDisputesRequest.SerializeToString,
                response_deserializer=dispute__pb2.ListDisputesResponse.FromString,
                _registered_method=True)
        self.MarkDisputeUnderReview = channel.unary_unary(
                '/dispute.DisputeService/MarkDisputeUnderReview',
                request_serializer=dispute__pb2.MarkDisputeUnderReviewRequest.SerializeToString,
                response_deserializer=dispute__pb2.DisputeResponse.FromString,
                _registered_method=True)
        self.RequestDisputeResolution = channel.unary_unary(
                '/dispute.DisputeService/RequestDisputeResolution',
                request_serializer=dispute__pb2.RequestDisputeResolutionRequest.SerializeToString,
                response_deserializer=dispute__pb2.DisputeResponse.FromString,
                _registered_method=True)
        self.ExecuteDisputeResolution = channel.unary_unary(
                '/dispute.DisputeService/ExecuteDisputeResolution',
                request_serializer=dispute__pb2.ExecuteDisputeResolutionRequest.SerializeToString,
                response_deserializer=dispute__pb2.DisputeResponse.FromString,
                _registered_method=True)


class DisputeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListDisputes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkDisputeUnderReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestDisputeResolution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteDisputeResolution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DisputeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDisputes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDisputes,
                    request_deserializer=dispute__pb2.ListDisputesRequest.FromString,
                    response_serializer=dispute__pb2.ListDisputesResponse.SerializeToString,
            ),
            'MarkDisputeUnderReview': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkDisputeUnderReview,
                    request_deserializer=dispute__pb2.MarkDisputeUnderReviewRequest.FromString,
                    response_serializer=dispute__pb2.DisputeResponse.SerializeToString,
            ),
            'RequestDisputeResolution': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestDisputeResolution,
                    request_deserializer=dispute__pb2.RequestDisputeResolutionRequest.FromString,
                    response_serializer=dispute__pb2.DisputeResponse.SerializeToString,
            ),
            'ExecuteDisputeResolution': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteDisputeResolution,
                    request_deserializer=dispute__pb2.ExecuteDisputeResolutionRequest.FromString,
                    response_serializer=dispute__pb2.DisputeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dispute.DisputeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dispute.DisputeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DisputeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDisputes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispute.DisputeService/ListDisputes',
            dispute__pb2.ListDisputesRequest.SerializeToString,
            dispute__pb2.ListDisputesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkDisputeUnderReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispute.DisputeService/MarkDisputeUnderReview',
            dispute__pb2.MarkDisputeUnderReviewRequest.SerializeToString,
            dispute__pb2.DisputeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestDisputeResolution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispute.DisputeService/RequestDisputeResolution',
            dispute__pb2.RequestDisputeResolutionRequest.SerializeToString,
            dispute__pb2.DisputeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteDisputeResolution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispute.DisputeService/ExecuteDisputeResolution',
            dispute__pb2.ExecuteDisputeResolutionRequest.SerializeToString,
            dispute__pb2.DisputeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
