# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dispute.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dispute.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdispute.proto\x12\x07\x64ispute\"B\n\x13ListDisputesRequest\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\"z\n\x14ListDisputesResponse\x12\'\n\x05items\x18\x01 \x03(\x0b\x32\x18.dispute.DisputeResponse\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\r\n\x05limit\x18\x04 \x01(\x05\x12\r\n\x05pages\x18\x05 \x01(\x05\"V\n\x1dMarkDisputeUnderReviewRequest\x12\x12\n\ndispute_id\x18\x01 \x01(\t\x12\x13\n\x0breviewer_id\x18\x02 \x01(\t\x12\x0c\n\x04note\x18\x03 \x01(\t\"t\n\x1fRequestDisputeResolutionRequest\x12\x12\n\ndispute_id\x18\x01 \x01(\t\x12\x10\n\x08\x61\x64min_id\x18\x02 \x01(\t\x12\x12\n\nresolution\x18\x03 \x01(\t\x12\x17\n\x0fresolution_note\x18\x04 \x01(\t\"[\n\x1f\x45xecuteDisputeResolutionRequest\x12\x12\n\ndispute_id\x18\x01 \x01(\t\x12\x12\n\nresolution\x18\x02 \x01(\t\x12\x10\n\x08\x61\x64min_id\x18\x03 \x01(\t\"\xcf\x01\n\x0f\x44isputeResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tescrow_id\x18\x02 \x01(\t\x12\x11\n\traised_by\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x17\n\x0fresolution_note\x18\x07 \x01(\t\x12\x13\n\x0bresolved_by\x18\x08 \x01(\t\x12\x13\n\x0bresolved_at\x18\t \x01(\t\x12\x12\n\ncreated_at\x18\n \x01(\t2\xf9\x02\n\x0e\x44isputeService\x12K\n\x0cListDisputes\x12\x1c.dispute.ListDisputesRequest\x1a\x1d.dispute.ListDisputesResponse\x12Z\n\x16MarkDisputeUnderReview\x12&.dispute.MarkDisputeUnderReviewRequest\x1a\x18.dispute.DisputeResponse\x12^\n\x18RequestDisputeResolution\x12(.dispute.RequestDisputeResolutionRequest\x1a\x18.dispute.DisputeResponse\x12^\n\x18\x45xecuteDisputeResolution\x12(.dispute.ExecuteDisputeResolutionRequest\x1a\x18.dispute.DisputeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dispute_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTDISPUTESREQUEST']._serialized_start=26
  _globals['_LISTDISPUTESREQUEST']._serialized_end=92
  _globals['_LISTDISPUTESRESPONSE']._serialized_start=94
  _globals['_LISTDISPUTESRESPONSE']._serialized_end=216
  _globals['_MARKDISPUTEUNDERREVIEWREQUEST']._serialized_start=218
  _globals['_MARKDISPUTEUNDERREVIEWREQUEST']._serialized_end=304
  _globals['_REQUESTDISPUTERESOLUTIONREQUEST']._serialized_start=306
  _globals['_REQUESTDISPUTERESOLUTIONREQUEST']._serialized_end=422
  _globals['_EXECUTEDISPUTERESOLUTIONREQUEST']._serialized_start=424
  _globals['_EXECUTEDISPUTERESOLUTIONREQUEST']._serialized_end=515
  _globals['_DISPUTERESPONSE']._serialized_start=518
  _globals['_DISPUTERESPONSE']._serialized_end=725
  _globals['_DISPUTESERVICE']._serialized_start=728
  _globals['_DISPUTESERVICE']._serialized_end=1105
# @@protoc_insertion_point(module_scope)
