# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.escrow_pb2 as escrow__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in escrow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EscrowServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEscrow = channel.unary_unary(
                '/escrow.EscrowService/GetEscrow',
                request_serializer=escrow__pb2.EscrowRequest.SerializeToString,
                response_deserializer=escrow__pb2.EscrowResponse.FromString,
                _registered_method=True)
        self.TransitionStatus = channel.unary_unary(
                '/escrow.EscrowService/TransitionStatus',
                request_serializer=escrow__pb2.TransitionRequest.SerializeToString,
                response_deserializer=escrow__pb2.EscrowResponse.FromString,
                _registered_method=True)
        self.AssociateUserWithEscrow = channel.unary_unary(
                '/escrow.EscrowService/AssociateUserWithEscrow',
                request_serializer=escrow__pb2.EscrowAssociationRequest.SerializeToString,
                response_deserializer=escrow__pb2.EscrowAssociationResponse.FromString,
                _registered_method=True)


class EscrowServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEscrow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransitionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssociateUserWithEscrow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EscrowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEscrow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEscrow,
                    request_deserializer=escrow__pb2.EscrowRequest.FromString,
                    response_serializer=escrow__pb2.EscrowResponse.SerializeToString,
            ),
            'TransitionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.TransitionStatus,
                    request_deserializer=escrow__pb2.TransitionRequest.FromString,
                    response_serializer=escrow__pb2.EscrowResponse.SerializeToString,
            ),
            'AssociateUserWithEscrow': grpc.unary_unary_rpc_method_handler(
                    servicer.AssociateUserWithEscrow,
                    request_deserializer=escrow__pb2.EscrowAssociationRequest.FromString,
                    response_serializer=escrow__pb2.EscrowAssociationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'escrow.EscrowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('escrow.EscrowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EscrowService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEscrow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/escrow.EscrowService/GetEscrow',
            escrow__pb2.EscrowRequest.SerializeToString,
            escrow__pb2.EscrowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransitionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/escrow.EscrowService/TransitionStatus',
            escrow__pb2.TransitionRequest.SerializeToString,
            escrow__pb2.EscrowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssociateUserWithEscrow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/escrow.EscrowService/AssociateUserWithEscrow',
            escrow__pb2.EscrowAssociationRequest.SerializeToString,
            escrow__pb2.EscrowAssociationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
