# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\x07storage\"\x92\x01\n\x14PresignUploadRequest\x12\x15\n\ractor_user_id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x0f\n\x07purpose\x18\x03 \x01(\t\x12\x12\n\nobject_key\x18\x04 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x05 \x01(\t\x12\x1a\n\x12\x65xpires_in_seconds\x18\x06 \x01(\x05\"~\n\x16PresignDownloadRequest\x12\x15\n\ractor_user_id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x0f\n\x07purpose\x18\x03 \x01(\t\x12\x12\n\nobject_key\x18\x04 \x01(\t\x12\x1a\n\x12\x65xpires_in_seconds\x18\x05 \x01(\x05\"\x83\x01\n\x12PresignUrlResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x0e\n\x06method\x18\x04 \x01(\t\x12\x12\n\nobject_key\x18\x05 \x01(\t\x12\x1a\n\x12\x65xpires_in_seconds\x18\x06 \x01(\x05\x32\xc8\x01\n\x0eStorageService\x12X\n\x1aGeneratePresignedUploadUrl\x12\x1d.storage.PresignUploadRequest\x1a\x1b.storage.PresignUrlResponse\x12\\\n\x1cGeneratePresignedDownloadUrl\x12\x1f.storage.PresignDownloadRequest\x1a\x1b.storage.PresignUrlResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRESIGNUPLOADREQUEST']._serialized_start=27
  _globals['_PRESIGNUPLOADREQUEST']._serialized_end=173
  _globals['_PRESIGNDOWNLOADREQUEST']._serialized_start=175
  _globals['_PRESIGNDOWNLOADREQUEST']._serialized_end=301
  _globals['_PRESIGNURLRESPONSE']._serialized_start=304
  _globals['_PRESIGNURLRESPONSE']._serialized_end=435
  _globals['_STORAGESERVICE']._serialized_start=438
  _globals['_STORAGESERVICE']._serialized_end=638
# @@protoc_insertion_point(module_scope)
