# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: admin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x64min.proto\x12\x05\x61\x64min\"4\n\x10\x46\x65\x65PolicyRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x03\x12\x10\n\x08who_pays\x18\x02 \x01(\t\"\xb3\x01\n\x11\x46\x65\x65PolicyResponse\x12\x12\n\nfee_amount\x18\x01 \x01(\x03\x12\x11\n\tbuyer_fee\x18\x02 \x01(\x03\x12\x12\n\nseller_fee\x18\x03 \x01(\x03\x12\x1c\n\x14platform_fee_percent\x18\x04 \x01(\x01\x12\x16\n\x0emin_fee_amount\x18\x05 \x01(\x03\x12\x16\n\x0emax_fee_amount\x18\x06 \x01(\x03\x12\x15\n\rused_override\x18\x07 \x01(\x08\x32W\n\x12\x41\x64minConfigService\x12\x41\n\x0cGetFeePolicy\x12\x17.admin.FeePolicyRequest\x1a\x18.admin.FeePolicyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEEPOLICYREQUEST']._serialized_start=22
  _globals['_FEEPOLICYREQUEST']._serialized_end=74
  _globals['_FEEPOLICYRESPONSE']._serialized_start=77
  _globals['_FEEPOLICYRESPONSE']._serialized_end=256
  _globals['_ADMINCONFIGSERVICE']._serialized_start=258
  _globals['_ADMINCONFIGSERVICE']._serialized_end=345
# @@protoc_insertion_point(module_scope)
